<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFrzogux\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFrzogux/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFrzogux.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFrzogux\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFrzogux\appDevDebugProjectContainer([
    'container.build_hash' => 'Frzogux',
    'container.build_id' => 'd65b6f3a',
    'container.build_time' => 1616255689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFrzogux');
