<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'FinanceBundle\Service\BaseService' shared autowired service.

include_once $this->targetDirs[3].'/src/FinanceBundle/Service/BaseService.php';

return $this->services['FinanceBundle\\Service\\BaseService'] = new \FinanceBundle\Service\BaseService();
