<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.jlaxwku' shared service.

return $this->services['service_locator.jlaxwku'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['baseService' => function () {
    $f = function (\FinanceBundle\Service\BaseService $v = null) { return $v; }; return $f(${($_ = isset($this->services['FinanceBundle\\Service\\BaseService']) ? $this->services['FinanceBundle\\Service\\BaseService'] : ($this->services['FinanceBundle\\Service\\BaseService'] = new \FinanceBundle\Service\BaseService())) && false ?: '_'});
}]);
