<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXx9ixcc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXx9ixcc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXx9ixcc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXx9ixcc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXx9ixcc\appProdProjectContainer([
    'container.build_hash' => 'Xx9ixcc',
    'container.build_id' => 'ad5c9b76',
    'container.build_time' => 1616291298,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXx9ixcc');
