<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7x8apkc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7x8apkc/appProdProjectContainer.php') {
    touch(__DIR__.'/Container7x8apkc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container7x8apkc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container7x8apkc\appProdProjectContainer([
    'container.build_hash' => '7x8apkc',
    'container.build_id' => '08f36fde',
    'container.build_time' => 1616256563,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7x8apkc');
